dependencies:
  - conda-forge::numpy=1.20
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.9
  - pip:
      - matplotlib==3.4.3
      - bilby
      - deepdish
      - legwork
      - tqdm
      - schwimmbad
      - cmasher
